// Layout tool: drag-reorder the children of the selected container. Writes the new JSX order back to source.
// Needs React 18 dev builds (fiber _debugSource) and children that are written out by hand in one file;
// children generated by .map() share one source position and are reported as not reorderable.
let box, offs = []

const esc = (value) => String(value).replace(/[&<>"']/g, (char) => ({
  '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
}[char]))

/** Source position of the JSX element that rendered a DOM node (React 18 dev), or null. */
export function positionOf(el) {
  const key = Object.keys(el).find((k) => k.startsWith('__reactFiber$'))
  const src = key && el[key]._debugSource
  return src?.fileName ? { fileName: src.fileName, line: src.lineNumber, column: src.columnNumber ?? 1 } : null
}

/** Decides whether a container's children can be reordered. Returns { ok, reason?, file?, positions? }. */
export function reorderPlan(positions) {
  if (positions.length < 2) return { ok: false, reason: 'Needs at least two child elements.' }
  if (positions.some((p) => !p)) return { ok: false, reason: 'Some children have no source info (need a React 18 dev build).' }
  const file = positions[0].fileName
  if (positions.some((p) => p.fileName !== file)) return { ok: false, reason: 'Children come from different files.' }
  const keys = positions.map((p) => `${p.line}:${p.column}`)
  if (new Set(keys).size !== keys.length) return { ok: false, reason: 'Children are generated by a loop; reorder the data instead.' }
  const sorted = [...positions].sort((a, b) => a.line - b.line || a.column - b.column)
  return { ok: true, file, sorted, positions }
}

export default {
  id: 'layout',
  name: 'Layout',
  hotkey: 'l',

  activate(api) {
    box = api.box({ outline: '2px solid #34d399' })
    api.panel.set('<b>Layout</b><div class="muted">Click a container. Drag its children to reorder them in source. Use Spacing for flex/grid, gap and alignment.</div>')
  },

  onSelect(container, api) {
    box.follow(container)
    const children = [...container.children]
    const positions = children.map(positionOf)
    const plan = reorderPlan(positions)
    if (!plan.ok) {
      api.panel.set(`<b>Layout · ${esc(api.selectorFor(container))}</b><div class="muted">${esc(plan.reason)}</div>`)
      return
    }
    // The page order and source order can differ (CSS order, conditional rendering); require they match.
    const inOrder = plan.sorted.every((p, i) => p === positions[i])
    if (!inOrder) {
      api.panel.set(`<b>Layout · ${esc(api.selectorFor(container))}</b><div class="muted">Children are not in the same order in source and on the page; reorder by hand.</div>`)
      return
    }
    api.panel.set(`<b>Layout · ${esc(api.selectorFor(container))}</b>
      <div class="muted" style="margin:4px 0 8px">Drag to reorder. The source file is rewritten on drop.</div>
      <div class="order-list">${children.map((child, i) => `<div class="scale-sample order-item" draggable="true" data-i="${i}" style="cursor:grab">
        <span>⠿ ${esc(child.tagName.toLowerCase())}${child.className && typeof child.className === 'string' ? '.' + esc(child.classList[0]) : ''}</span>
        <small>${esc((child.textContent || '').trim().slice(0, 40))}</small></div>`).join('')}</div>
      <div class="muted msg"></div>`)
    const list = api.panel.el.querySelector('.order-list')
    let dragging = null
    list.querySelectorAll('.order-item').forEach((item) => {
      item.ondragstart = (event) => { dragging = Number(item.dataset.i); event.dataTransfer.effectAllowed = 'move' }
      item.ondragover = (event) => event.preventDefault()
      item.ondrop = async (event) => {
        event.preventDefault()
        const to = Number(item.dataset.i)
        if (dragging == null || dragging === to) return
        const msg = api.panel.el.querySelector('.msg')
        try {
          const rel = positions[0].fileName
          await api.rpc('move', {
            file: rel,
            positions: positions.map((p) => ({ line: p.line, column: p.column })),
            from: dragging,
            to,
          })
          msg.textContent = 'Reordered. The page will reload with the new order.'
        } catch (error) {
          msg.textContent = 'Error: ' + error.message
        }
        dragging = null
      }
    })
  },

  deactivate() {
    offs.forEach((off) => off())
    offs = []
    box?.destroy()
  },
}
